# Title of the Site
title: Jacobs Alumni Association

# general meta data
description: The Jacobs Alumni Association is the growing network of former Jacobs University students and friends.
keywords: Jacobs Alumni Association, Jacobs University Bremen, Jacobs University, Alumni Association, Jacobs, Alumni, Association, Bremen

# We support UTF-8, for all the unicode stuff
encoding: utf-8

# Exlude all the README.md files -- they are for documentation
# also exclude the license
exclude:
    - '*/README.md'
    - 'LICENSE'
    - 'src/board/member.html'
    - 'src/board/oldmember.html'
    - 'src/imprint/president.html'
    - 'src/imprint/vice_president.html'
    - 'src/imprint/treasurer.html'
    - 'src/imprint/secretary.html'
    - 'src/imprint/accessors.html'


collections:
  - faqs

# Google Analytics
#googleAnalyticsID: "UA-136384959-1"

# default values -- the one for all **must** be first
defaults:
  -
    scope:
      path: ""
    values:
      layout: default


plugins:
- jekyll-redirect-from


# the menu
menu:
  - title: Home
    url: /
  - title: Board
    url: /board/
  - title: Homecoming
    url: /homecoming/
  - title: Chapters
    url: /chapters/
  - title: Get involved
    url: /get-involved/
  - title: Donate
    url: /donate/
  - title: Documents
    url: /documents/
  - title: FAQ
    url: /faq/
  - title: Join
    external: true
    url: https://portal.jacobs-alumni.de/
  - title: Alumni Portal
    external: true
    url: https://portal.jacobs-alumni.de/portal/