# Title of the Site
title: Jacobs Alumni Association

# general meta data
description: The Jacobs Alumni Association is the growing network of former Jacobs University students and friends.
keywords: Jacobs Alumni Association, Jacobs University Bremen, Jacobs University, Alumni Association, Jacobs, Alumni, Association, Bremen

# We support UTF-8, for all the unicode stuff
encoding: utf-8

# Exlude all the README.md files -- they are for documentation
# also exclude the license
exclude:
    - '*/README.md'
    - 'LICENSE'

# Google Analytics
googleAnalyticsID: "UA-136384959-1"

# default values -- the one for all **must** be first
defaults:
  -
    scope:
      path: ""
    values:
      layout: default

# the menu
menu:
  - title: Home
    url: /
  - title: Board
    url: /board/
  - title: Activities
    url: /activities/
  - title: Documents
    url: /documents/
  - title: FAQ
    url: /faq/
  - title: Contribute
    url: /contribute/
  - title: Join
    external: true
    url: https://portal.jacobs-alumni.de